engines:
  eslint:
    enabled: true
    checks:
      import/extensions:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
    exclude_fingerprints:
      - 6214f6f329b74c779a236048fa0c595b
      - 72b6d969d0c80e43b3362e7e9906bfb5
  fixme:
    enabled: true
ratings:
  paths:
    - "src/**/*"
    - "**.js"
exclude_paths:
  - ".idea"
  - ".nyc-output"
  - "build"
  - "coverage"
  - "docs"
  - "licenses"
  - "node_modules"
  - "test"
  - "tools"
  - "src/server/data/types"
