language: node_js
node_js:
  - '6'
  - '5'
env:
  - CXX=g++-4.8
addons:
  code_climate: true
  apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.8
before_script:
 - npm install -g codeclimate-test-reporter
script:
  - npm run lint
  - npm run test:cover
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
