language: node_js
node_js:
  - '6'
  - '5'
addons:
  code_climate: true
before_script:
 - npm install -g codeclimate-test-reporter
 - npm install
script:
  - npm run lint
  - npm run test:cover
after_script:
  - CODECLIMATE_REPO_TOKEN=${CODECLIMATE_REPO_TOKEN} codeclimate-test-reporter < lcov.info
